<a href="https://colab.research.google.com/github/caoTayTang/image_super_resolution_traditional_cv/blob/main/notebooks/experiments_ml_patch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import sys
import os
import numpy as np
sys.path.append(os.path.abspath('..'))
from src import utils
from src import ml_patch


In [8]:
# Classify images into degraded_lr and input_hr folders
base_dir = '../data/jbhuang0604 SelfExSR master data/BSD100'
output_dir = ['../data/degraded_lr', '../data/input_hr']
utils.img_classify(base_dir, output_dir)

SRF_2 done: 200 images processed.
SRF_3 done: 200 images processed.
SRF_4 done: 200 images processed.


In [ ]:
# Chia patches from degraded_lr and input_hr folders và lưu giá trị RGB của nó
base_dir = ['../data/degraded_lr', '../data/input_hr']
output_dir = '../data/RGB'
ml_patch.process_all_patches(base_dir, output_dir, patch_size=5, overlap=0.5)


Extracted 920400 LR patches and 920400 HR patches
Saved LR/HR patches for scale x2 to ../data/RGB
Extracted 405600 LR patches and 405600 HR patches
Saved LR/HR patches for scale x3 to ../data/RGB
Extracted 220400 LR patches and 220400 HR patches
Saved LR/HR patches for scale x4 to ../data/RGB


In [14]:
LR_patches = np.load(os.path.join(output_dir, 'LR_patches_x2.npy'))
HR_patches = np.load(os.path.join(output_dir, 'HR_patches_x2.npy'))
print("LR patch 0 shape:", LR_patches[0].shape)
print(LR_patches[0])  # in giá trị pixel
print("LR patch 1 shape:", LR_patches[1].shape)
print(LR_patches[1])  # in giá trị pixel
print("HR patch 0 shape:", HR_patches[0].shape)
print(HR_patches[0])

LR patch 0 shape: (5, 5, 3)
[[[238 241 241]
  [254 255 255]
  [254 254 254]
  [255 255 255]
  [216 217 218]]

 [[255 254 255]
  [254 253 254]
  [253 255 255]
  [246 252 251]
  [161 171 171]]

 [[255 252 255]
  [253 254 255]
  [250 255 255]
  [184 199 193]
  [108 126 121]]

 [[253 255 255]
  [248 255 253]
  [212 227 217]
  [158 181 167]
  [133 158 146]]

 [[221 238 234]
  [203 221 212]
  [184 205 190]
  [195 219 202]
  [195 222 205]]]
LR patch 1 shape: (5, 5, 3)
[[[254 254 254]
  [255 255 255]
  [216 217 218]
  [241 245 245]
  [251 255 255]]

 [[253 255 255]
  [246 252 251]
  [161 171 171]
  [214 221 221]
  [255 255 255]]

 [[250 255 255]
  [184 199 193]
  [108 126 121]
  [181 194 192]
  [254 255 255]]

 [[212 227 217]
  [158 181 167]
  [133 158 146]
  [163 183 174]
  [243 253 249]]

 [[184 205 190]
  [195 219 202]
  [195 222 205]
  [200 227 211]
  [176 198 185]]]
HR patch 0 shape: (10, 10, 3)
[[[196 200 201]
  [251 255 255]
  [253 255 255]
  [252 254 254]
  [253 253 253]
  [255 255 255